// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPYLouyXbfksRKiN9UwDS6iNG2iTbqh2c',
    appId: '1:1012992072548:web:f5ef8e1510309e12133871',
    messagingSenderId: '1012992072548',
    projectId: 'proyecto-1ca8a',
    authDomain: 'proyecto-1ca8a.firebaseapp.com',
    storageBucket: 'proyecto-1ca8a.appspot.com',
    measurementId: 'G-RMPWJDPY4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiW_JXHm66rg5ovphdJBpsCNcrwJQn_KU',
    appId: '1:1012992072548:android:97b974461f5e6105133871',
    messagingSenderId: '1012992072548',
    projectId: 'proyecto-1ca8a',
    storageBucket: 'proyecto-1ca8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2mJj2Dd-LRYxfsubydEPmIpx3f442y6A',
    appId: '1:1012992072548:ios:b7495165f0902560133871',
    messagingSenderId: '1012992072548',
    projectId: 'proyecto-1ca8a',
    storageBucket: 'proyecto-1ca8a.appspot.com',
    iosBundleId: 'com.example.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2mJj2Dd-LRYxfsubydEPmIpx3f442y6A',
    appId: '1:1012992072548:ios:466cbe39be89455b133871',
    messagingSenderId: '1012992072548',
    projectId: 'proyecto-1ca8a',
    storageBucket: 'proyecto-1ca8a.appspot.com',
    iosBundleId: 'com.example.proyecto.RunnerTests',
  );
}
